---
user: <%= ENV.fetch("PG_USERNAME") { "postgres" } %>
password: <%= ENV.fetch("PG_PASSWORD") { "" } %>
host: <%= ENV.fetch("PG_HOST") { "localhost" } %>
database: 'open-licitaciones'
adapter: 'postgres'
